version: '3.1'

services:

  db:
    image: postgres:latest
    networks:
      - dev-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_files/db_data:/var/lib/postgresql/data
      - ./db_files/init-database.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"

networks:
  dev-network:
    driver: bridge