import Head from "next/head";
import React from "react";
import BackendLayout from "../../components/Layout/BackendLayout";
// import {setActivePageAction} from "../../redux/layouts";
import { ListItems } from "../../components/Locations";

export default function Locations() {
  return (
    <>
      <Head>
        <title>MapKids - Locations</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h2 className="mt-10 text-lg font-medium intro-y">Locations List</h2>
      <ListItems />
    </>
  );
}

Locations.Layout = BackendLayout;

export async function getServerSideProps() {
  const locale = "en";

  return {
    props: {
      locale,
    },
  };
}
